services:
    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: discord-stats
        volumes:
            - postgres_data:/var/lib/postgres/data
        ports:
            - 5432:5432
        restart: unless-stopped

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./sqlite.db:/var/lib/grafana/sqlite
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
        restart: unless-stopped

volumes:
    postgres_data:
    grafana_data:
